# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/persons.html

# persons: 
#   - name: Andy
#     track: person.dwain
#     picture_path: 'images/persons/dwain.jpg'
#     more_entities:
#       columns: 1 #optional
#       entities:
#         - entity: sensor.steps
#         - entity: sensor.steps
#     page_entities:
#       columns: 2 #optional
#       entities:
#         - entity: sensor.steps
#         - entity: sensor.steps