esphome:
  name: ble_node_2
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "Home.Local.Wireless"
  password: "J3llyt0ts"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ble Node 2 Fallback Hotspot"
    password: "ejgsIqYPaBrS"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "J$llyt0ts"

ota:
  password: "J$llyt0ts"

esp32_ble_tracker:

binary_sensor:
  - platform: ble_presence
    mac_address: 24:6F:28:9D:E6:42
    name: "ESP32 BLE Tracker"
  - platform: ble_presence
    mac_address: 68:23:09:D2:41:7F
    name: "Andy Mobile Tracker"

sensor:
  - platform: ble_rssi
    mac_address: 24:6F:28:9D:E6:42
    name: "BLE RSSI value"
  - platform: ble_rssi
    mac_address: 68:23:09:D2:41:7F
    name: "Andy Mobile RSSI value"
